travis:
  secure:
    BINSTAR_TOKEN: CtNoYt4iIFCGNfXxU1zx90V3qFbrRoWYdvf3nQnYE4UgDpctHF6fbRWnsECWWuI4DVeIO/APO3HlO7blpR/XSaHR8MLv3XE7mjZ0eUj/y8n+bhiFgbkZN1hGCqHaqnE1PiO1CeXpOHnyITjNpuyi0OHQzbQpwkhcViCDzbNcjf0tD9q1tymfObRPeml66bU8NOzCMslEUuZknDH5ReE1rJDSXFfdAhEMlHN6hukeuZTBIlzDXgOPpdoH6lCgSikdS/ujH5Iy3HrbmIp/03stNKeDVNocjTPVkAYY/tOo3QsV8fEI8fABEejS4h/HLd5PsU+il1XHcA0xE0DPLQUs43Wc+XtpN+xN7+zzC+X6upbOPGl5MGMK7CpdmFdO+2cJRjvWL7JREmr0TNHXojQSVUDxdKHy7GPHloxTIKLGR09Bs9BHpDMNYQmm6ksWzwh9O/yMUh6gAtHxZlumnQVb46cpB7BzAiR4LhCG9NKfbkHAqcJSF7QCyEOGQNE4AecOYf8ZcmquHAleaeuo+6aYMD8HgYuIvSeqpOS5hJQrvroVDxTbNFmTBekHOMP78ufhVKdD+eHvOXwozh75UDiyYFW0wIotduXVJGYzjC43wz2CXKveJjWGJ0qIo3CBiWRItxisskikD/Ec5JKcFL5KGvfo6ffhoL6oSp8sd+LUIW8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
