travis:
  secure:
    BINSTAR_TOKEN: hnjyJMNan/d5Vv130SbR1Lz10USHXKcLGJWmWkJILPxhd+rYb7XWPuIHupRPuZfIlTLNk822Le2m20YchsKfdvCibTpEHV0BdlLNFp2OEvJyu4CWXirfJy4NtSwILeiyS5G+LxaWj3Y7xStJ3MUkQpPzpGkP8Oa+NL9C7cUeUmR7I5YEm4lno7OnHO/XQz3eZ+idoKjAIRQB/mHh3nXYyRDod04sWZDWGJXqBB/RMMpb2bI0a8foWH5OB5glBYUng4+D18l//jhTuqaqx3eGMd1b4Ahh0fJgzuCBl3BgyuzjSs3g4prWG/eL9TNmYisiEaNQKA4QrO3XvQ2oIwetJeZEy18aWpZiVGE1V9aKuOojxskfImV5YOCiQXoXtMR109t9v1kIntodJHjkNQ547sw0WGURs8J9P2cl+4DkDy+sa9vPoDCbE9KHiD+UqfXgUXk2VNsZL9cjT1iYv9MqUzcDi9LGh/lNCuQCitj2nakGFMTJPDnwEZfNX6H1e0NQ+4Mu9WMbuRuKpjKlj/dESZRAO6lVZsuI2rYOHpaF8MfSChzhOmsbf4B1eIS7TP+xBNQXqY1Ggn1XSsgYzRP6EbfB56QwmzE4Ab+AyxJ1lGbFH+HONlV5bnTywgXObAamit7VfbxDcXrpVG7zLj94Tg6G+85MVz1XSDTm+ltjA5c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
